# CMake script to convert a binary file to a C/C++ header
# Arguments: INPUT_FILE, OUTPUT_FILE, VAR_NAME

if(NOT INPUT_FILE OR NOT OUTPUT_FILE OR NOT VAR_NAME)
    message(FATAL_ERROR "Usage: cmake -DINPUT_FILE=... -DOUTPUT_FILE=... -DVAR_NAME=... -P bin2c.cmake")
endif()

file(READ ${INPUT_FILE} HEX_CONTENT HEX)

string(REGEX MATCHALL "([0-9a-f][0-9a-f])" HEX_PAIRS "${HEX_CONTENT}")

set(C_CONTENT "/* Generated by bin2c.cmake */\n")
set(C_CONTENT "${C_CONTENT}#include <stdint.h>\n\n")
set(C_CONTENT "${C_CONTENT}static const uint32_t ${VAR_NAME}[] = {\n    ")

set(COL_COUNT 0)
set(WORD "")
set(BYTE_COUNT 0)

foreach(PAIR ${HEX_PAIRS})
    # SPIR-V is a stream of 32-bit words. 
    # file(READ HEX) provides bytes in file order: B0, B1, B2, B3...
    # We want to form a 32-bit word. In C, 0x03020100 is B0, B1, B2, B3 on Little Endian.
    set(WORD "${PAIR}${WORD}")
    math(EXPR BYTE_COUNT "${BYTE_COUNT} + 1")
    
    if(BYTE_COUNT EQUAL 4)
        set(C_CONTENT "${C_CONTENT}0x${WORD}, ")
        set(WORD "")
        set(BYTE_COUNT 0)
        
        math(EXPR COL_COUNT "${COL_COUNT} + 1")
        if(COL_COUNT EQUAL 6)
            set(C_CONTENT "${C_CONTENT}\n    ")
            set(COL_COUNT 0)
        endif()
    endif()
endforeach()

# Handle remaining bytes if any (shouldn't happen for valid SPV)
if(NOT WORD STREQUAL "")
    set(C_CONTENT "${C_CONTENT}0x${WORD}, ")
endif()

set(C_CONTENT "${C_CONTENT}\n};\n")
set(C_CONTENT "${C_CONTENT}static const uint32_t ${VAR_NAME}_size = sizeof(${VAR_NAME});\n")

file(WRITE ${OUTPUT_FILE} "${C_CONTENT}")
