package com.hinnka.mycamera.raw

import kotlin.math.ln

/**
 * Plans Photon PGTM metadata for the sampled Local Laplacian + bilateral-grid pipeline.
 *
 * The image-dependent mapping is generated by the compute passes in
 * [DngPhotonLocalToneMapGpuShaders]. [DngPhotonLocalToneMapper] remains the readable CPU reference
 * used to compare equations and constants; it is not used by the capture path.
 */
internal object DngPhotonProfileGainTableGenerator {
    private const val MIN_TABLE_GAIN = 1f / 4096f
    private const val MAX_TABLE_GAIN = 4096f

    fun plan(
        grid: HdrPgtmGrid,
        pointCount: Int,
        baselineExposureEv: Float,
        samplingArea: HdrPgtmSamplingArea = HdrPgtmSamplingArea.FULL,
        diagnosticBand: DngHdrProfileGainTableGenerator.DiagnosticBand?,
    ): HdrProfileGainTablePlan {
        val exposureGain = DngBaselineExposure.exactGain(baselineExposureEv)
        // CELL_STATS samples one non-overlapping 16x16 block per spatial table entry. Locate the
        // entries at those block centers; values outside the first/last center are edge-clamped by
        // DNG renderers, matching the BGU input boundary condition.
        val spacingH = samplingArea.extentH / grid.mapPointsH
        val spacingV = samplingArea.extentV / grid.mapPointsV
        val centeredGrid = grid.copy(
            mapSpacingH = spacingH,
            mapSpacingV = spacingV,
            mapOriginH = samplingArea.originH + 0.5 * spacingH,
            mapOriginV = samplingArea.originV + 0.5 * spacingV,
        )
        // DNG renderers include BaselineExposure before calculating the table coordinate.
        // Dividing the weights by that exact gain makes the BGU guide the sampled source-linear
        // scene input, while the gain itself still acts on the exposed signal.
        val mapWeights = FloatArray(DngHdrProfileGainTableGenerator.BASE_INPUT_WEIGHTS.size) {
            DngHdrProfileGainTableGenerator.BASE_INPUT_WEIGHTS[it] / exposureGain
        }
        return HdrProfileGainTablePlan(
            curveModel = HdrPgtmCurveModel.PHOTON,
            grid = centeredGrid,
            pointCount = pointCount,
            mapInputWeights = mapWeights,
            gamma = 1f,
            googlePlan = null,
            photonPlan = PhotonPgtmPlan(
                exposureGain = exposureGain,
                minTableGain = MIN_TABLE_GAIN,
                maxTableGain = MAX_TABLE_GAIN,
                parameters = PhotonLocalToneMappingParameters(),
            ),
            diagnosticBand = diagnosticBand,
        )
    }
}

/**
 * Parameters copied from the published Local Laplacian and Google BGU reference code.
 *
 * The Local Laplacian edge slope is the compression ratio required to reach the reference target
 * dynamic range. ACR3's fixed +1.1 EV gray placement is applied to scene-linear input before Local
 * Laplacian; scene highlights therefore do not determine exposure. The resulting SDR target is
 * then projected directly into ProfileGainTableMap's RGB-uniform multiplicative representation.
 * The MATLAB example's final display gamma is omitted because output encoding is performed by the
 * renderer after the DNG profile pipeline.
 */
internal data class PhotonLocalToneMappingParameters(
    // Paris, Hasinoff, Kautz 2011 HDR example: sigma=2.5 in linear space and alpha=1.
    val localLaplacianRangeSigma: Float = ln(2.5).toFloat(),
    val localLaplacianDetailExponent: Float = 1f,
    // Aubry et al. llf_general.m example for a general remapping function.
    val localLaplacianIntensityLevels: Int = 20,
    // Paris et al. tone-map postprocessing.
    val percentileClip: Float = 0.005f,
    val targetDynamicRange: Float = 100f,
    // Places scene-linear 0.18 at 0.18 * 2^1.25 before Local Laplacian processing.
    val preToneMapExposureBoostEv: Float = 1.25f,
    // Google BGU production estimates.
    val bilateralSpatialBinSize: Int = 16,
    val bilateralRangeSigma: Float = 1f / 8f,
    val bilateralGuideCurveAlpha: Float = 0.8f,
    // Current Halide BGU uses a fixed 1/10-sample identity prior. The older
    // count-scaled average-gain prior was removed upstream because it regularized
    // well-populated cells more strongly and under-populated cells less strongly.
    val bilateralRegularization: Float = 0.1f,
) {
    init {
        require(localLaplacianRangeSigma.isFinite() && localLaplacianRangeSigma > 0f)
        require(localLaplacianDetailExponent.isFinite() && localLaplacianDetailExponent > 0f)
        require(localLaplacianIntensityLevels >= 2)
        require(percentileClip.isFinite() && percentileClip in 0f..<0.5f)
        require(targetDynamicRange.isFinite() && targetDynamicRange > 1f)
        require(preToneMapExposureBoostEv.isFinite())
        require(bilateralSpatialBinSize > 0)
        require(bilateralRangeSigma.isFinite() && bilateralRangeSigma > 0f)
        require(bilateralGuideCurveAlpha.isFinite() && bilateralGuideCurveAlpha in 0f..1f)
        require(bilateralRegularization.isFinite() && bilateralRegularization > 0f)
    }
}

internal data class PhotonPgtmPlan(
    val exposureGain: Float,
    val minTableGain: Float,
    val maxTableGain: Float,
    val parameters: PhotonLocalToneMappingParameters,
) {
    init {
        require(exposureGain.isFinite() && exposureGain > 0f)
        require(minTableGain.isFinite() && minTableGain > 0f)
        require(maxTableGain.isFinite() && maxTableGain >= minTableGain)
    }
}
