package com.hinnka.mycamera.previewhook.api

import com.hinnka.mycamera.model.ColorRecipeParams

data class MgcPreviewRecipeParams(
    val lutIntensity: Float = 1f,
    val exposure: Float = 0f,
    val contrast: Float = 1f,
    val saturation: Float = 1f,
    val temperature: Float = 0f,
    val tint: Float = 0f,
    val fade: Float = 0f,
    val color: Float = 0f,
    val highlights: Float = 0f,
    val shadows: Float = 0f,
    val toneToe: Float = 0f,
    val toneShoulder: Float = 0f,
    val tonePivot: Float = 0f,
    val paletteX: Float = 0.5f,
    val paletteY: Float = 0.5f,
    val paletteDensity: Float = 1f,
    val filmGrain: Float = 0f,
    val vignette: Float = 0f,
    val bleachBypass: Float = 0f,
    val halation: Float = 0f,
    val chromaticAberration: Float = 0f,
    val noise: Float = 0f,
    val lowRes: Float = 0f,
    val skinHue: Float = 0f,
    val skinChroma: Float = 0f,
    val skinLightness: Float = 0f,
    val redHue: Float = 0f,
    val redChroma: Float = 0f,
    val redLightness: Float = 0f,
    val orangeHue: Float = 0f,
    val orangeChroma: Float = 0f,
    val orangeLightness: Float = 0f,
    val yellowHue: Float = 0f,
    val yellowChroma: Float = 0f,
    val yellowLightness: Float = 0f,
    val greenHue: Float = 0f,
    val greenChroma: Float = 0f,
    val greenLightness: Float = 0f,
    val cyanHue: Float = 0f,
    val cyanChroma: Float = 0f,
    val cyanLightness: Float = 0f,
    val blueHue: Float = 0f,
    val blueChroma: Float = 0f,
    val blueLightness: Float = 0f,
    val purpleHue: Float = 0f,
    val purpleChroma: Float = 0f,
    val purpleLightness: Float = 0f,
    val magentaHue: Float = 0f,
    val magentaChroma: Float = 0f,
    val magentaLightness: Float = 0f,
    val remarks: String = "",
) {
    fun toColorRecipeParams(): ColorRecipeParams {
        return ColorRecipeParams(
            lutIntensity = lutIntensity,
            exposure = exposure,
            contrast = contrast,
            saturation = saturation,
            temperature = temperature,
            tint = tint,
            fade = fade,
            color = color,
            highlights = highlights,
            shadows = shadows,
            toneToe = toneToe,
            toneShoulder = toneShoulder,
            tonePivot = tonePivot,
            paletteX = paletteX,
            paletteY = paletteY,
            paletteDensity = paletteDensity,
            filmGrain = filmGrain,
            vignette = vignette,
            bleachBypass = bleachBypass,
            halation = halation,
            chromaticAberration = chromaticAberration,
            noise = noise,
            lowRes = lowRes,
            skinHue = skinHue,
            skinChroma = skinChroma,
            skinLightness = skinLightness,
            redHue = redHue,
            redChroma = redChroma,
            redLightness = redLightness,
            orangeHue = orangeHue,
            orangeChroma = orangeChroma,
            orangeLightness = orangeLightness,
            yellowHue = yellowHue,
            yellowChroma = yellowChroma,
            yellowLightness = yellowLightness,
            greenHue = greenHue,
            greenChroma = greenChroma,
            greenLightness = greenLightness,
            cyanHue = cyanHue,
            cyanChroma = cyanChroma,
            cyanLightness = cyanLightness,
            blueHue = blueHue,
            blueChroma = blueChroma,
            blueLightness = blueLightness,
            purpleHue = purpleHue,
            purpleChroma = purpleChroma,
            purpleLightness = purpleLightness,
            magentaHue = magentaHue,
            magentaChroma = magentaChroma,
            magentaLightness = magentaLightness,
            remarks = remarks,
        )
    }
}
